services:
  odoo:
    build: .
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo@123
    volumes:
      - odoo-data:/var/lib/odoo:rw
      - ./odoo/odoo:/usr/lib/python3/dist-packages/odoo:ro
      - ./odoo:/opt/odoo:ro
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./extra-addons:/mnt/extra-addons:ro
    restart: always
    networks:
      - odoo-net

  db:
    image: postgres:14
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo@123
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    restart: always
    networks:
      - odoo-net

volumes:
  odoo-data:
  db-data:

networks:
  odoo-net:
    driver: bridge
